(define (make-table)
  (let ((local-table (list '*table*)))
    (define (lookup keys)
      (let ((key (car keys)))
	(if (null? (cdr keys))
	    ;;(set! local-table (list '*table* (
    (define (insert! keys value)
      (let ((key (car keys))
	    (backbone (cdr local-table)
      'ok)    
    (define (dispatch m)
      (cond ((eq? m 'lookup-proc) lookup)
            ((eq? m 'insert-proc!) insert!)
            (else (error "Unknown operation -- TABLE" m))))
    dispatch))
