(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define call-the-cops "Wee woo wee woo")
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
	  ((eq? m 'deposit) deposit)
	  (else (error "Unknown request -- MAKE-ACCOUNT"
		       m))))
  (let ((attempts 0)
	(max-attempts 7))
    (lambda (p m)
      (if (eq? p password)
	  (begin (set! attempts 0)
		 (dispatch m))
	  (begin
	    (set! attempts (+ attempts 1))
	    (if (> attempts max-attempts)
		(lambda (x) call-the-cops)
		(lambda (x) "Incorrect password")))))))

