(define (RLC R L C dt)
  (lambda (vc0 il0)
    (define vc (integral (delay dvc) vc0 dt))
    (define il (integral (delay dil) il0 dt))
    (define dil (add-streams (scale-stream vc (/ 1 L)) (scale-stream il (/ (- R) L))))
    (define dvc (scale-stream il (/ -1 C)))
    (cons vc il)))

(define circuit (RLC 1 1 .2 .1))
(define states (circuit 10 0))
