(define (make-register name)
  (let ((contents '*unassigned*)
	(trace? false))
    (define (set-contents! value) ;no return value
      (if trace?
	  (trace value))
      (set! contents value))
    (define (trace value)
      (newline)
      (display (list 'register: name 'old-contents: contents 'new-contents: value)))
    (define (dispatch message)
      (cond ((eq? message 'get) contents)
            ((eq? message 'set) set-contents!)
	    ((eq? message 'trace-on) (set! trace? true) 'trace-on)
	    ((eq? message 'trace-off) (set! trace? false) 'trace-off)
            (else
             (error "Unknown request -- REGISTER" message))))
    dispatch))

(define (make-new-machine)
  (let ((pc (make-register 'pc))
        (flag (make-register 'flag))
        (stack (make-stack))
        (the-instruction-sequence '())
	(instructions-executed 0)
	(trace? false))
    (let ((the-ops
           (list (list 'initialize-stack
                       (lambda () (stack 'initialize)))))
          (register-table
           (list (list 'pc pc) (list 'flag flag))))
      (define (allocate-register name)
        (if (assoc name register-table)
            (error "Multiply defined register: " name)
            (set! register-table
                  (cons (list name (make-register name))
                        register-table)))
        'register-allocated)
      (define (lookup-register name)
        (let ((val (assoc name register-table)))
          (if val
              (cadr val)
              (error "Unknown register:" name))))
      (define (trace inst)
	(if (not (null? (instruction-label inst)))
	    (begin (newline)
		   (display (instruction-label inst))))
	(newline)
	(display (instruction-text inst)))
      (define (execute)
        (let ((insts (get-contents pc)))
          (if (null? insts)
              'done
              (let ((inst (car insts)))
		(if trace?
		    (trace inst))
		(set! instructions-executed (+ instructions-executed 1))
                ((instruction-execution-proc (car insts)))
                (execute)))))
      (define (dispatch message)
        (cond ((eq? message 'start)
	       (set! instructions-executed 0)
               (set-contents! pc the-instruction-sequence)
               (execute))
              ((eq? message 'install-instruction-sequence)
               (lambda (seq) (set! the-instruction-sequence seq)))
              ((eq? message 'allocate-register) allocate-register)
              ((eq? message 'get-register) lookup-register)
              ((eq? message 'install-operations)
               (lambda (ops) (set! the-ops (append the-ops ops))))
              ((eq? message 'stack) stack)
              ((eq? message 'operations) the-ops)
	      ((eq? message 'instructions-executed) instructions-executed)
	      ((eq? message 'trace-on) (set! trace? true) 'trace-on)
	      ((eq? message 'trace-off) (set! trace? false) 'trace-off)
	      ((eq? message 'trace-on-reg)
	       (lambda (reg-name) ((lookup-register reg-name) 'trace-on)))
	      ((eq? message 'trace-off-reg)
	       (lambda (reg-name) ((lookup-register reg-name) 'trace-off)))
              (else (error "Unknown request -- MACHINE" message))))
      dispatch)))
